"""remove tabela respostas_quiz

Revision ID: 35cc49519661
Revises: 81ea6eb0aa48
Create Date: 2026-05-29 09:33:03.796075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35cc49519661'
down_revision = '81ea6eb0aa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respostas_quiz',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pontuacao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_resposta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('respostas_quiz_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('respostas_quiz_pkey'))
    )
    # ### end Alembic commands ###
