"""Cria tabelas do simulador

Revision ID: 5b8b410f2d60
Revises: af661eab794a
Create Date: 2026-05-30 21:51:29.577469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8b410f2d60'
down_revision = 'af661eab794a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simuladores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cenarios_simulador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=False),
    sa.Column('simulador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulador_id'], ['simuladores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_simulador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.Column('estado_final', sa.String(length=50), nullable=False),
    sa.Column('primeira_resposta', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('simulador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulador_id'], ['simuladores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcoes_simulador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('cenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cenario_id'], ['cenarios_simulador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opcoes_simulador')
    op.drop_table('resultados_simulador')
    op.drop_table('cenarios_simulador')
    op.drop_table('simuladores')
    # ### end Alembic commands ###
