"""cria tabelas do quiz

Revision ID: 81ea6eb0aa48
Revises: c7dadcb2896c
Create Date: 2026-05-29 09:26:13.174339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ea6eb0aa48'
down_revision = 'c7dadcb2896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pergunta', sa.Text(), nullable=False))
        batch_op.alter_column('alternativa_a',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_b',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_c',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_d',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('enunciado')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enunciado', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('alternativa_d',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('alternativa_c',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('alternativa_b',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('alternativa_a',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('pergunta')

    op.drop_table('resultados_quiz')
    # ### end Alembic commands ###
