"""adiciona foreign key quiz em perguntas

Revision ID: af661eab794a
Revises: bfb9e752c9da
Create Date: 2026-05-30 17:34:06.243505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af661eab794a'
down_revision = 'bfb9e752c9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
