"""atualiza tabela perguntas quiz

Revision ID: bfb9e752c9da
Revises: 35cc49519661
Create Date: 2026-05-30 17:29:30.588212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb9e752c9da'
down_revision = '35cc49519661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enunciado', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('alternativa_correta', sa.String(length=1), nullable=False))
        batch_op.alter_column('alternativa_a',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('alternativa_b',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('alternativa_c',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('alternativa_d',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('perguntas_quiz_quiz_id_fkey'), type_='foreignkey')
        batch_op.drop_column('quiz_id')
        batch_op.drop_column('resposta_correta')
        batch_op.drop_column('pergunta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pergunta', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resposta_correta', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('perguntas_quiz_quiz_id_fkey'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.alter_column('alternativa_d',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_c',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_b',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('alternativa_a',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('alternativa_correta')
        batch_op.drop_column('enunciado')

    # ### end Alembic commands ###
