"""cria tabelas do quiz

Revision ID: c7dadcb2896c
Revises: 6c032e25a6df
Create Date: 2026-05-29 09:16:58.016161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dadcb2896c'
down_revision = '6c032e25a6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('alternativa_a', sa.String(length=120), nullable=False),
    sa.Column('alternativa_b', sa.String(length=120), nullable=False),
    sa.Column('alternativa_c', sa.String(length=120), nullable=False),
    sa.Column('alternativa_d', sa.String(length=120), nullable=False),
    sa.Column('resposta_correta', sa.String(length=1), nullable=False),
    sa.Column('explicacao', sa.Text(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_quiz')
    op.drop_table('perguntas_quiz')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
